name = "JuliaAdventOfCode"
uuid = "3c4f75d9-6e88-4e04-8445-e7dd8734ba30"
authors = ["Eric Burden <eric@ericburden.dev>"]
version = "0.1.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
